[package]
name = "rest_api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.12.1"
dotenv = "0.15.0"
env_logger = "0.11.8"
serde = { version = "1.0.228", features = ["derive"] }
sqlx = { version = "0.8.6", features = ["postgres","runtime-async-std"] }
